language: ruby
sudo: false
rvm:
- 1.9.3
- 2.3.1
- jruby-9.1.1.0
env:
  global:
  - COVERAGE=1
matrix:
  allow_failures:
  - rvm: jruby-9.1.1.0
services:
- redis-server
notifications:
  irc:
    channels:
    - 'chat.freenode.net#resque'
    on_success: change
    on_failure: change
deploy:
  provider: rubygems
  api_key:
    secure: dM97lL/jTu14mEHD2Ih/vQfZ8cWJWb+DQ8UKZjkD2JfYtvwEAlkPG9RrrDkSHb5qkYxG2VAhjyx/0MZJ0TsVL6wrLMC9gcJb3yomw2Sch2Noj68tEndiSUHnxrB9gKzbhHbjLQXDqYf4Hco9/PHHQp4piFPJhLzNZRehIuTJPcA=
  gem: resque-scheduler
  on:
    tags: true
    repo: resque/resque-scheduler
    rvm: 2.3.1
    all_branches: true
